version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: projectraihan
      POSTGRES_PASSWORD: webdev_test
      POSTGRES_DB: work-order-db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080 # sets the adminer port to 9000
